### ISSUE TITLE
为什么不能在sdk中提供生成认证串的API？

### ISSUE THREAD

**Issue by yelikang** [INFE/BosPublicUpload#3]
为什么不能在sdk中提供生成认证串的API？自己写累死也搞不对。
总报：
![image](https://cloud.githubusercontent.com/assets/11992275/11434495/6130b5c0-9508-11e5-8838-50c3a9e78110.png)

**Comment by chendatony31** [comment]
我们提供认证的api会有安全问题，所以没有提供
